azure:
  keyvault:
    uri: https://jcasample.vault.azure.net/                # The URI to the Azure Key Vault used
    tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47          # The Tenant ID for your Azure Key Vault (needed if you are not using managed identity).
    client-id: a136e6c3-be04-49ca-979e-ead0b3df7d22          # The Client ID that has been setup with access to your Azure Key Vault (needed if you are not using managed identity).
    client-secret:      # The Client Secret that will be used for accessing your Azure Key Vault (needed if you are not using managed identity).
    # managed-identity:  # The user-assigned managed identity object-id to use.
server:
  port: 8080
  ssl:
    enabled: false